# Generated by Django 5.0.2 on 2025-07-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_galleryimage_delete_uploadedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('image1', 'Image1'), ('image2', 'Image2'), ('image3', 'Image3'), ('image4', 'Image4')], max_length=10),
        ),
    ]
